spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ms_user_management_db
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

server:
  port : 9091

UserController:
  signup: Creates user and returns its JWT token
  delete: Deletes specific user by username
  search: Returns specific user by username
